name = "dt-trading"
pages_build_output_dir = "dist"
compatibility_date = "2024-02-14"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "car2"
database_id = "638b867c-9171-45be-9d65-63db3a0dd842"

# R2 Storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "carr2"
